_wandb:
    value:
        cli_version: 0.30.0
        e:
            822zwhmsoci914kwh6ecllbullelowpg:
                args:
                    - --config
                    - ../config/config.yaml
                    - --max-code-len
                    - "512"
                    - --max-sum-len
                    - "128"
                codePath: src/train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "982240026624"
                        used: "326178500608"
                email: pigidanti@gmail.com
                executable: /home/pier/MLSA_codeSummarization/.venv/bin/python3
                git:
                    commit: 34ac1eef97b7055b9eecc4f2200b1bee6f789732
                    remote: git@github.com:FabioPoggialiBerlinghieri/MLSA_codeSummarization.git
                gpu: NVIDIA T500
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA T500
                      uuid: GPU-9d9ce203-2347-a0d0-82f2-a642603eb322
                host: pier-ThinkPad-P14s-Gen-2i
                memory:
                    total: "16471560192"
                os: Linux-7.0.0-31-generic-x86_64-with-glibc2.39
                program: /home/pier/MLSA_codeSummarization/src/train.py
                python: CPython 3.11.16
                root: /home/pier/MLSA_codeSummarization/src
                startedAt: "2026-09-13T18:53:06.966948Z"
                writerId: 822zwhmsoci914kwh6ecllbullelowpg
        m: []
        python_version: 3.11.16
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 100
            "2":
                - 1
                - 11
                - 49
                - 51
                - 100
            "3":
                - 1
                - 16
            "4": 3.11.16
            "5": 0.30.0
            "6": 5.16.1
            "12": 0.30.0
            "13": linux-x86_64
batch_size:
    value: 128
best_bleu_path:
    value: ../models/checkpoint_best_bleu.pt
best_loss_path:
    value: ../models/checkpoint_best_loss.pt
checkpoint_path:
    value: ../models/checkpoint_latest.pt
dataset_config:
    value: python
dataset_link:
    value: google/code_x_glue_ct_code_to_text
dataset_test_path:
    value: ../data/dataset_test.json
dataset_train_path:
    value: ../data/dataset_train.json
dataset_val_path:
    value: ../data/dataset_validation.json
dataset_x:
    value: code
dataset_y:
    value: docstring
english_voc_path:
    value: ../data/english_vocab.json
epochs:
    value: 50
first_time:
    value: false
learning_rate:
    value: 0.0003
model:
    value:
        code_voc_len: 30000
        dropout: 0.2
        embedding_dim: 512
        input_vocabulary_size: 30000
        max_code_len: 512
        max_text_len: 128
        num_heads: 8
        num_layers: 4
        output_vocabulary_size: 30000
        text_voc_len: 30000
python_voc_path:
    value: ../data/code_vocab.json
split_test:
    value: test
split_train:
    value: train
split_val:
    value: validation
