dataset_link: google-research-datasets/mbpp
dataset_train_path: ../data/dataset_train.json
dataset_val_path: ../data/dataset_validation.json
dataset_test_path: ../data/dataset_test.json
python_voc_path: ../data/code_vocab.json
english_voc_path: ../data/english_vocab.json
first_time: false
learning_rate: 0.001
epochs: 200
batch_size: 64
checkpoint_path: ../models/checkpoint_latest.pt
best_loss_path: ../models/checkpoint_best_loss.pt
best_bleu_path: ../models/checkpoint_best_bleu.pt
model:
  embedding_dim: 512
  input_vocabulary_size: 30000
  output_vocabulary_size: 30000
