dataset_link: google/code_x_glue_ct_code_to_text
dataset_config: python
dataset_x: code
dataset_y: docstring
split_train: train
split_val: validation
split_test: test
dataset_train_path: ../data/dataset_train.json
dataset_val_path: ../data/dataset_validation.json
dataset_test_path: ../data/dataset_test.json
python_voc_path: ../data/code_vocab.json
english_voc_path: ../data/english_vocab.json
first_time: false
learning_rate: 0.0003
epochs: 50
batch_size: 128
checkpoint_path: ../models/checkpoint_latest.pt
best_loss_path: ../models/checkpoint_best_loss.pt
best_bleu_path: ../models/checkpoint_best_bleu.pt
model:
  dropout: 0.2
  embedding_dim: 512
  input_vocabulary_size: 30000
  output_vocabulary_size: 30000
  num_layers: 4
  num_heads: 8
